#!/usr/bin/env python
import argparse

import ikwi

parser = argparse.ArgumentParser(description="A personal wiki.")
parser.add_argument('command')
parser.add_argument('repo')

args = parser.parse_args()

site = ikwi.Ikwi(args.repo)
command = args.command.lower()

if command == 'run':
    site.run()
